class_name SimReport
extends RefCounted
## Turns a batch of careers into the two things the brief asks for: a compact table on
## stdout and a full markdown report on disk.
##
## Findings are DERIVED, never hard-coded: every line below fires off a measured number, so
## a data-only tuning commit changes the findings without anybody editing this file.

const MINUTE := 60.0
const HOUR := 3600.0

## Effect kinds the projection can put a dollar value on. A node built only out of the
## others cannot lose a purchase comparison it was never in.
const PRICEABLE: PackedStringArray = [
	"value_mult", "value_add", "idle_rate_add", "launder_rate_add", "launder_cap_add",
	"pocket_money_set", "passive_wash_add", "safe_hours_set", "ball_save_charges",
	"tilt_leans_add", "flipper_power_mult", "kickback_unlock", "collect_minutes_mult",
	"unlock_hardware", "feature_flag",
]


## `careers`: profile id -> Array[SimCareer]. Returns the console text.
static func console(careers: Dictionary, targets: Array[Dictionary], catalog: Upgrades,
		days: int, seeds: PackedInt64Array, elapsed_ms: int) -> String:
	var out := PackedStringArray()
	out.append("KINGPIN balance run — %d days, %d profile(s), seeds %s (%.1fs)" % [
			days, careers.size(), _seed_text(seeds), float(elapsed_ms) / 1000.0])
	for id in SimProfile.ids():
		if not careers.has(id):
			continue
		var runs: Array = careers[id]
		if runs.is_empty():
			continue
		var lead := runs[0] as SimCareer
		out.append("")
		out.append("== %s — %s" % [lead.profile.label.to_upper(), lead.profile.note])
		out.append(_career_table(lead, false))
		out.append(_profile_line(runs))
	out.append("")
	out.append("== TARGETS (docs/03 §9)")
	out.append(_targets_table(targets, false))
	out.append("")
	out.append("== FINDINGS")
	for line in findings(careers, catalog):
		out.append("  " + line)
	return "\n".join(out)


static func markdown(careers: Dictionary, targets: Array[Dictionary], catalog: Upgrades,
		days: int, seeds: PackedInt64Array, elapsed_ms: int) -> String:
	var out := PackedStringArray()
	out.append("# KINGPIN — balance report")
	out.append("")
	out.append("Generated by `game/sim/balance_cli.gd` (`tools/balance.sh`). %d simulated days, "
			% days + "seeds %s, %d profiles, %.1fs of wall clock." % [
			_seed_text(seeds), careers.size(), float(elapsed_ms) / 1000.0])
	out.append("")
	out.append("The economy under test is the shipped one: real `Upgrades` catalog, real `Stats`, "
			+ "`Wallet`, `HeatMeter`, `Combo`, `Jobs`, `Bench`, `Reveal`, `Rates` and `Offline`. "
			+ "Only the source of switch events is modelled (see `game/sim/profiles.json`).")
	out.append("")
	out.append("Catalog: `%s` — %d nodes." % [
			catalog.source if catalog.source != "" else Upgrades.DEFAULT_PATH, catalog.nodes.size()])
	if not SimState.skill_shot_scales_with_rank:
		out.append("")
		out.append("**Counterfactual run (`--flat-skill`): the skill shot is pinned to its R0 value "
				+ "instead of `rank_scale(rank)/rank_scale(0)` (×10 per rank).**")
	out.append("")
	out.append("## Targets (docs/03 §9)")
	out.append("")
	out.append(_targets_table(targets, true))
	out.append("")
	out.append("## Findings")
	out.append("")
	for line in findings(careers, catalog):
		out.append("- " + line)
	for id in SimProfile.ids():
		if not careers.has(id):
			continue
		var runs: Array = careers[id]
		if runs.is_empty():
			continue
		var lead := runs[0] as SimCareer
		out.append("")
		out.append("## %s" % lead.profile.label)
		out.append("")
		out.append("_%s_" % lead.profile.note)
		out.append("")
		out.append(_career_table(lead, true))
		out.append("")
		out.append(_profile_line(runs))
		out.append("")
		out.append("### Where the money came from")
		out.append("")
		out.append(_group_table(lead, true))
		out.append("")
		out.append("### Purchase order (seed %d)" % lead.seed_value)
		out.append("")
		out.append(_purchase_table(lead, true))
	out.append("")
	out.append("## Profile parameters")
	out.append("")
	out.append(_profile_table(careers, true))
	out.append("")
	return "\n".join(out)


# --- findings -------------------------------------------------------------------------


static func findings(careers: Dictionary, catalog: Upgrades) -> PackedStringArray:
	var out := PackedStringArray()
	var dead := SimTargets.dead_nodes(careers, catalog)
	if dead.is_empty():
		out.append("Every node in the catalog was bought by somebody by the end of the run.")
	else:
		out.append("DEAD NODES (%d/%d never bought by any profile): %s" % [
				dead.size(), catalog.nodes.size(), ", ".join(dead)])
	var core := SimTargets.core_nodes(careers)
	if not core.is_empty():
		out.append("Bought by every profile on every seed (%d): %s" % [core.size(), ", ".join(core)])

	for id in SimProfile.ids():
		if not careers.has(id):
			continue
		var runs: Array = careers[id]
		if runs.is_empty():
			continue
		var c := runs[0] as SimCareer
		var s := c.state
		out.append("%s: peak heat %.1f (band %d) — %s" % [id, s.peak_heat,
				Rates.band_for(s.peak_heat),
				"the Heat dial never left band 0, so the ×1.5/×2.5/×4 multipliers and the Raid are dead content at this income scale"
				if s.peak_heat < Rates.BAND_THRESHOLDS[0]
				else "the risk band is live"])
		var pocket_share := s.total_pocket.ratio_to(s.total_clean_earned) if s.total_clean_earned.is_positive() else 0.0
		out.append("%s: clean earned %s, of which %.0f%% is pocket money (the R0 grace)" % [
				id, s.total_clean_earned.text(), pocket_share * 100.0])
		if s.capped_possible > 0:
			out.append("%s: laundering cap spent in %d of %d Nights that had one; %d of %d wash "
					% [id, s.capped_nights, s.capped_possible, c.wash_dead, c.wash_passes]
					+ "shots (%.0f%%) then washed nothing at all"
					% (100.0 * float(c.wash_dead) / maxf(float(c.wash_passes), 1.0)))
		out.append("%s: ☆%d over %d Nights (%.0f/Night) — %s" % [
				id, s.respect, c.nights_played,
				float(s.respect) / maxf(float(c.nights_played), 1.0), _respect_mix(s)])
		var top := _top_group(c)
		if not top.is_empty():
			out.append("%s: %s alone is %.0f%% of career dirty (%s of %s)" % [
					id, String(top["group"]), float(top["share"]) * 100.0,
					(top["amount"] as BigMoney).text(), _career_dirty(c).text()])
		out.append("%s: %d Nights, %d shots, %.0f%% of them wasted (dead target / shuttered storefront)" % [
				id, c.nights_played, c.shots_fired,
				100.0 * float(c.wasted_shots) / maxf(float(c.shots_fired), 1.0)])
		if s.short_lineups == 0 and c.nights_played > 0:
			out.append("%s: %d Nights, %d guys pinched, and never once a short line-up — a "
					% [id, c.nights_played, s.guys_pinched]
					+ "4-guy Bench with a 1-Night sit-out always refills before the next roll "
					+ "call, so the docs/03 §8 bail sink never fires")
	var unpriced := _unpriceable(SimTargets.dead_nodes(careers, catalog), catalog)
	if not unpriced.is_empty():
		out.append("Of the dead nodes, these have no effect this sim can price (Respect, bench "
				+ "depth, job slips): %s — they are invisible to an income-maximising bot, "
				% ", ".join(unpriced) + "which is a limit of the model, not proof they are junk")
	return out


static func _unpriceable(ids: PackedStringArray, catalog: Upgrades) -> PackedStringArray:
	var out: PackedStringArray = []
	for id in ids:
		var node := catalog.def(id)
		if node.is_empty():
			continue
		var priced := false
		for effect: Variant in node["effects"] as Array:
			if PRICEABLE.has(String((effect as Dictionary)["kind"])):
				priced = true
		if not priced:
			out.append(id)
	return out


# --- tables ---------------------------------------------------------------------------


static func _career_table(c: SimCareer, md: bool) -> String:
	var head := PackedStringArray(["day", "rank", "☆", "nights", "dirty/day", "clean/day",
			"held dirty", "held clean", "nodes", "play"])
	var rows: Array[PackedStringArray] = []
	for r in c.rows:
		rows.append(PackedStringArray([
			str(r["day"]), "R%d" % int(r["rank"]), str(r["respect"]), str(r["nights"]),
			(r["dirty_day"] as BigMoney).text(), (r["clean_day"] as BigMoney).text(),
			(r["dirty_held"] as BigMoney).text(), (r["clean_held"] as BigMoney).text(),
			"%d/%d" % [int(r["nodes"]), int(r["levels"])],
			"%.0fm" % (float(r["play_seconds"]) / MINUTE),
		]))
	return _render(head, rows, md)


static func _profile_line(runs: Array) -> String:
	var c := runs[0] as SimCareer
	var ranks := PackedStringArray()
	for rank in range(1, 8):
		var t := c.rank_clock(rank)
		if t >= 0.0:
			ranks.append("R%d @ %.1fh" % [rank, t / HOUR])
	return "  %d seeds · median Night %.1f min · active %s/h · idle %s/h · %s" % [
			runs.size(), c.median_night_seconds() / MINUTE, c.last_day_per_hour().text(),
			c.idle_per_hour().text(), " · ".join(ranks) if ranks.size() > 0 else "no rank-ups"]


static func _group_table(c: SimCareer, md: bool) -> String:
	var head := PackedStringArray(["source", "career dirty", "share"])
	var total := _career_dirty(c)
	var keys: Array = c.by_group.keys()
	keys.sort_custom(func(a: Variant, b: Variant) -> bool:
		return (c.by_group[a] as BigMoney).cmp(c.by_group[b] as BigMoney) > 0)
	var rows: Array[PackedStringArray] = []
	for g: Variant in keys:
		var amount: BigMoney = c.by_group[g]
		rows.append(PackedStringArray([String(g), amount.text(),
				"%.1f%%" % (amount.ratio_to(total) * 100.0)]))
	var idle := c.state.total_idle
	rows.append(PackedStringArray(["idle (rackets + Safe)", idle.text(),
			"%.1f%%" % (idle.ratio_to(total) * 100.0)]))
	return _render(head, rows, md)


static func _purchase_table(c: SimCareer, md: bool) -> String:
	var head := PackedStringArray(["#", "night", "node", "lvl", "cost", "rank", "play"])
	var rows: Array[PackedStringArray] = []
	var i := 0
	for p in c.state.purchases:
		i += 1
		rows.append(PackedStringArray([str(i), str(int(p["night"])), String(p["id"]),
				str(int(p["level"])), (p["cost"] as BigMoney).text(), "R%d" % int(p["rank"]),
				"%.0fm" % (float(p["play"]) / MINUTE)]))
	if rows.is_empty():
		return "_nothing was ever bought._"
	return _render(head, rows, md)


static func _targets_table(targets: Array[Dictionary], md: bool) -> String:
	var head := PackedStringArray(["profile", "metric", "target", "measured", "verdict", "note"])
	var rows: Array[PackedStringArray] = []
	for t in targets:
		rows.append(PackedStringArray([String(t["profile"]), String(t["metric"]),
				String(t["target"]), String(t["got"]), String(t["verdict"]), String(t["note"])]))
	return _render(head, rows, md)


static func _profile_table(careers: Dictionary, md: bool) -> String:
	var head := PackedStringArray(["profile", "ball s", "sw/s", "tilt", "skill", "discipline",
			"spin kick", "wash", "sessions/day", "nights"])
	var rows: Array[PackedStringArray] = []
	for id in SimProfile.ids():
		if not careers.has(id) or (careers[id] as Array).is_empty():
			continue
		var p := ((careers[id] as Array)[0] as SimCareer).profile
		rows.append(PackedStringArray([p.label, "%.0f" % p.ball_seconds_mean,
				"%.1f" % p.switches_per_sec, "%.0f%%" % (p.tilt_per_ball * 100.0),
				"%.0f%%" % (p.skill_shot_p * 100.0), "%.0f%%" % (p.target_discipline * 100.0),
				"%.0f" % p.spinner_kick_speed, "%.0f%%" % (p.wash_share * 100.0),
				"%.1f" % p.sessions_per_day, str(p.nights_per_session)]))
	return _render(head, rows, md)


# --- helpers ----------------------------------------------------------------------------


static func _career_dirty(c: SimCareer) -> BigMoney:
	return c.state.total_dirty


## Where the ☆ came from, biggest first — the rank ladder is only as sane as this mix.
static func _respect_mix(s: SimState) -> String:
	var keys: Array = s.total_respect_from.keys()
	keys.sort_custom(func(a: Variant, b: Variant) -> bool:
		return int(s.total_respect_from[a]) > int(s.total_respect_from[b]))
	var parts := PackedStringArray()
	for k: Variant in keys:
		parts.append("%s %.0f%%" % [String(k),
				100.0 * float(s.total_respect_from[k]) / maxf(float(s.respect), 1.0)])
	return ", ".join(parts)


static func _top_group(c: SimCareer) -> Dictionary:
	var total := _career_dirty(c)
	var best := BigMoney.zero()
	var name := ""
	for g: Variant in c.by_group:
		var amount: BigMoney = c.by_group[g]
		if amount.cmp(best) > 0:
			best = amount
			name = String(g)
	if name == "" or not total.is_positive():
		return {}
	return {"group": name, "amount": best, "share": best.ratio_to(total)}


static func _seed_text(seeds: PackedInt64Array) -> String:
	var out := PackedStringArray()
	for s in seeds:
		out.append(str(s))
	return ", ".join(out)


static func _render(head: PackedStringArray, rows: Array[PackedStringArray], md: bool) -> String:
	var widths: PackedInt32Array = []
	for h in head:
		widths.append(h.length())
	for r in rows:
		for i in r.size():
			if i < widths.size():
				widths[i] = maxi(widths[i], r[i].length())
	var out := PackedStringArray()
	out.append(_line(head, widths, md))
	if md:
		var sep := PackedStringArray()
		for w in widths:
			sep.append("-".repeat(maxi(w, 3)))
		out.append(_line(sep, widths, true))
	else:
		var sep2 := PackedStringArray()
		for w in widths:
			sep2.append("-".repeat(w))
		out.append(_line(sep2, widths, false))
	for r in rows:
		out.append(_line(r, widths, md))
	return "\n".join(out)


static func _line(cells: PackedStringArray, widths: PackedInt32Array, md: bool) -> String:
	var parts := PackedStringArray()
	for i in cells.size():
		var w := widths[i] if i < widths.size() else cells[i].length()
		parts.append(cells[i].rpad(w))
	if md:
		return "| " + " | ".join(parts) + " |"
	return "  " + "  ".join(parts)
