class_name SimReport
extends RefCounted
## Turns a batch of careers into the two things the brief asks for: a compact table on
## stdout and a full markdown report on disk.
##
## Findings are DERIVED, never hard-coded: every line below fires off a measured number, so
## a data-only tuning commit changes the findings without anybody editing this file.

const MINUTE := 60.0
const HOUR := 3600.0

## Effect kinds the projection can put a dollar value on. A node built only out of the
## others cannot lose a purchase comparison it was never in.
const PRICEABLE: PackedStringArray = [
	"value_mult", "value_add", "idle_rate_add", "launder_rate_add", "launder_cap_add",
	"pocket_money_set", "passive_wash_add", "safe_hours_set", "ball_save_charges",
	"tilt_leans_add", "flipper_power_mult", "kickback_unlock", "collect_minutes_mult",
	"unlock_hardware", "feature_flag",
	# M2 specialists (specs/m2-content.md §2). The rest of the vocabulary —
	# `bail_discount`, `job_reroll_add`, `job_respect_mult`, `aim_line` — buys Respect,
	# rerolls or a ghost line, none of which the projection can turn into dollars per Night.
	"casino_edge_add", "casino_pocket_add", "auto_launder_per_sec", "auto_collect_interval",
	"serve_speed_mult", "kickback_cooldown_mult", "all_dirty_mult", "heat_decay_mult",
]


## `careers`: profile id -> Array[SimCareer]. Returns the console text.
static func console(careers: Dictionary, targets: Array[Dictionary], catalog: Upgrades,
		days: int, seeds: PackedInt64Array, elapsed_ms: int) -> String:
	var out := PackedStringArray()
	out.append("KINGPIN balance run — %d days, %d profile(s), seeds %s (%.1fs)" % [
			days, careers.size(), _seed_text(seeds), float(elapsed_ms) / 1000.0])
	for id in SimProfile.ids():
		if not careers.has(id):
			continue
		var runs: Array = careers[id]
		if runs.is_empty():
			continue
		var lead := runs[0] as SimCareer
		out.append("")
		out.append("== %s — %s" % [lead.profile.label.to_upper(), lead.profile.note])
		out.append(_career_table(lead, false))
		out.append(_profile_line(runs))
	out.append("")
	out.append("== TARGETS (docs/03 §9)")
	out.append(_targets_table(targets, false))
	out.append("")
	out.append("== THE CLUB (specs/m2-content.md §1/§4)")
	out.append(_club_table(careers, false))
	out.append("")
	out.append("== WHERE CLEAN COMES FROM")
	out.append(_clean_table(careers, false))
	out.append("")
	out.append("== HEAT (docs/03 §4)")
	out.append(_heat_table(careers, false))
	out.append("")
	out.append("== THE COMMISSION (docs/05 §6)")
	out.append(_commission_table(careers, false))
	out.append("")
	out.append("== FINDINGS")
	for line in findings(careers, catalog):
		out.append("  " + line)
	return "\n".join(out)


static func markdown(careers: Dictionary, targets: Array[Dictionary], catalog: Upgrades,
		days: int, seeds: PackedInt64Array, elapsed_ms: int) -> String:
	var out := PackedStringArray()
	out.append("# KINGPIN — balance report")
	out.append("")
	out.append("Generated by `game/sim/balance_cli.gd` (`tools/balance.sh`). %d simulated days, "
			% days + "seeds %s, %d profiles, %.1fs of wall clock." % [
			_seed_text(seeds), careers.size(), float(elapsed_ms) / 1000.0])
	out.append("")
	out.append("The economy under test is the shipped one: real `Upgrades` catalog, real `Stats`, "
			+ "`Wallet`, `HeatMeter`, `Combo`, `Jobs`, `Bench`, `Reveal`, `Rates` and `Offline`. "
			+ "Only the source of switch events is modelled (see `game/sim/profiles.json`).")
	out.append("")
	out.append("Catalog: `%s` — %d nodes." % [
			catalog.source if catalog.source != "" else Upgrades.DEFAULT_PATH, catalog.nodes.size()])
	var switches := PackedStringArray()
	if SimState.skill_shot_scales_with_rank:
		switches.append("`--rank-skill`: the skill shot is back on `rank_scale(rank)/rank_scale(0)` "
				+ "(×10 per rank), the behaviour the M1 sim retired")
	if SimState.clean_eats_wash_cap:
		switches.append("`--capped-clean`: money paid through `earn_clean` (casino wins, Jackpots, "
				+ "Meeting jackpots, exact Wire numbers) counts against the per-Night wash cap")
	if not switches.is_empty():
		out.append("")
		out.append("**COUNTERFACTUAL RUN — this is not the shipped economy:**")
		out.append("")
		for s in switches:
			out.append("- " + s)
	out.append("")
	out.append("## Targets (docs/03 §9)")
	out.append("")
	out.append(_targets_table(targets, true))
	out.append("")
	out.append("## The Club")
	out.append("")
	out.append("Deck visits, the wheel's book and the Family Meeting's uptime. `action` is every "
			+ "dollar the wheel spun on — the player's stakes plus the house's comped ones — and "
			+ "`EV real` is what came back per dollar of it, against the "
			+ "`Casino.expected_value(stats)` the end-state build had bought.")
	out.append("")
	out.append(_club_table(careers, true))
	out.append("")
	out.append("## Where clean comes from")
	out.append("")
	out.append("The wash cap (docs/03 §2) binds only on money that was DIRTY first. "
			+ "`earn_clean` money — casino wins under the Wash, Jackpots, Meeting jackpots, "
			+ "exact Wire numbers, boss purses — never touches it.")
	out.append("")
	out.append(_clean_table(careers, true))
	out.append("")
	out.append("## Heat")
	out.append("")
	out.append(_heat_table(careers, true))
	out.append("")
	out.append("## The Commission")
	out.append("")
	out.append(_commission_table(careers, true))
	out.append("")
	out.append("## Tier bands, measured")
	out.append("")
	out.append("What a Night and a day of clean income actually is, late — the input to the "
			+ "T6/T7 cost bands (docs/03 §7).")
	out.append("")
	out.append(_income_table(careers, true))
	out.append("")
	out.append("## Findings")
	out.append("")
	for line in findings(careers, catalog):
		out.append("- " + line)
	for id in SimProfile.ids():
		if not careers.has(id):
			continue
		var runs: Array = careers[id]
		if runs.is_empty():
			continue
		var lead := runs[0] as SimCareer
		out.append("")
		out.append("## %s" % lead.profile.label)
		out.append("")
		out.append("_%s_" % lead.profile.note)
		out.append("")
		out.append(_career_table(lead, true))
		out.append("")
		out.append(_profile_line(runs))
		out.append("")
		out.append("### Where the money came from")
		out.append("")
		out.append(_group_table(lead, true))
		out.append("")
		out.append("### Purchase order (seed %d)" % lead.seed_value)
		out.append("")
		out.append(_purchase_table(lead, true))
	out.append("")
	out.append("## Profile parameters")
	out.append("")
	out.append(_profile_table(careers, true))
	out.append("")
	return "\n".join(out)


# --- findings -------------------------------------------------------------------------


static func findings(careers: Dictionary, catalog: Upgrades) -> PackedStringArray:
	var out := PackedStringArray()
	var dead := SimTargets.dead_nodes(careers, catalog)
	if dead.is_empty():
		out.append("Every node in the catalog was bought by somebody by the end of the run.")
	else:
		out.append("DEAD NODES (%d/%d never bought by any profile): %s" % [
				dead.size(), catalog.nodes.size(), ", ".join(dead)])
	var core := SimTargets.core_nodes(careers)
	if not core.is_empty():
		out.append("Bought by every profile on every seed (%d): %s" % [core.size(), ", ".join(core)])

	for id in SimProfile.ids():
		if not careers.has(id):
			continue
		var runs: Array = careers[id]
		if runs.is_empty():
			continue
		var c := runs[0] as SimCareer
		var s := c.state
		out.append("%s: peak heat %.1f (band %d) — %s" % [id, s.peak_heat,
				Rates.band_for(s.peak_heat),
				"the Heat dial never left band 0, so the ×1.5/×2.5/×4 multipliers and the Raid are dead content at this income scale"
				if s.peak_heat < Rates.BAND_THRESHOLDS[0]
				else "the risk band is live"])
		var pocket_share := s.total_pocket.ratio_to(s.total_clean_earned) if s.total_clean_earned.is_positive() else 0.0
		out.append("%s: clean earned %s, of which %.0f%% is pocket money (the R0 grace)" % [
				id, s.total_clean_earned.text(), pocket_share * 100.0])
		if s.capped_possible > 0:
			out.append("%s: laundering cap spent in %d of %d Nights that had one; %d of %d wash "
					% [id, s.capped_nights, s.capped_possible, c.wash_dead, c.wash_passes]
					+ "shots (%.0f%%) then washed nothing at all"
					% (100.0 * float(c.wash_dead) / maxf(float(c.wash_passes), 1.0)))
		out.append("%s: ☆%d over %d Nights (%.0f/Night) — %s" % [
				id, s.respect, c.nights_played,
				float(s.respect) / maxf(float(c.nights_played), 1.0), _respect_mix(s)])
		var by_shot := BigMoney.zero()
		for g: Variant in c.by_group:
			by_shot = by_shot.add(c.by_group[g])
		var off_shot := _career_dirty(c).sub_clamped(by_shot).sub_clamped(s.total_idle)
		if off_shot.is_positive():
			out.append("%s: %s of career dirty (%s) arrived without a switch closing — mode "
					% [id, off_shot.text(), _pct(off_shot, _career_dirty(c))]
					+ "payouts: the Collection Round's double, a Wire draw, a casino win with "
					+ "the Wash unbought")
		var top := _top_group(c)
		if not top.is_empty():
			out.append("%s: %s alone is %.0f%% of career dirty (%s of %s)" % [
					id, String(top["group"]), float(top["share"]) * 100.0,
					(top["amount"] as BigMoney).text(), _career_dirty(c).text()])
		out.append("%s: %d Nights, %d shots, %.0f%% of them wasted (dead target / shuttered storefront)" % [
				id, c.nights_played, c.shots_fired,
				100.0 * float(c.wasted_shots) / maxf(float(c.shots_fired), 1.0)])
		if s.short_lineups == 0 and c.nights_played > 0:
			out.append("%s: %d Nights, %d guys pinched, and never once a short line-up — a "
					% [id, c.nights_played, s.guys_pinched]
					+ "4-guy Bench with a 1-Night sit-out always refills before the next roll "
					+ "call, so the docs/03 §8 bail sink never fires")
	out.append_array(_club_findings(careers))
	var unpriced := _unpriceable(SimTargets.dead_nodes(careers, catalog), catalog)
	if not unpriced.is_empty():
		out.append("Of the dead nodes, these have no effect this sim can price (Respect, bench "
				+ "depth, job slips): %s — they are invisible to an income-maximising bot, "
				% ", ".join(unpriced) + "which is a limit of the model, not proof they are junk")
	return out


## Derived from the measured Club numbers, one line per thing the M2 wave has to answer.
static func _club_findings(careers: Dictionary) -> PackedStringArray:
	var out := PackedStringArray()
	for id in SimProfile.ids():
		if not careers.has(id) or (careers[id] as Array).is_empty():
			continue
		var c := (careers[id] as Array)[0] as SimCareer
		var s := c.state
		if s.casino_spins <= 0:
			out.append("%s: never reached the Club — no deck, no wheel, no Meeting" % id)
			continue
		var built := Casino.expected_value(s.stats)
		# Action, not out-of-pocket: comped stakes are the house's money on the same wheel.
		var action := s.casino_staked.add(s.casino_comped_staked)
		var real := s.casino_paid.ratio_to(action) - 1.0 if action.is_positive() else 0.0
		var avg_mult := s.casino_mult_sum / maxf(float(s.casino_wins), 1.0)
		out.append("%s: %d spins put %s across the wheel and paid %s — realized EV %+.1f%% against the %+.1f%% "
				% [id, s.casino_spins, action.text(), s.casino_paid.text(),
				real * 100.0, built * 100.0]
				+ "the end-state build had bought (%d/%d pockets at ×%.2f)"
				% [Casino.player_pockets(s.stats), Casino.CasinoRules.POCKETS,
				Casino.payout_rate(s.stats)])
		out.append("%s: a winning spin paid ×%.2f on average against a wheel payout of ×%.2f — "
				% [id, avg_mult, Casino.payout_rate(s.stats)]
				+ "%d fired Coolers are the only thing that can be on top of it, and the %d "
				% [s.casino_coolers, s.high_roller_holds]
				+ "High Roller holds moved the BET (%s of comped action is in the EV above)"
				% s.casino_comped_staked.text())
		var casino_clean := _clean_from(s, &"roulette_wheel")
		if s.total_clean_earned.is_positive():
			out.append("%s: the wheel alone is %.0f%% of career CLEAN (%s of %s); everything "
					% [id, casino_clean.ratio_to(s.total_clean_earned) * 100.0,
					casino_clean.text(), s.total_clean_earned.text()]
					+ "paid through `earn_clean` is %.0f%%, and none of it touches the wash cap"
					% (s.total_clean_direct.ratio_to(s.total_clean_earned) * 100.0))
		var band_live := 0.0
		var total_band := 0.0
		for i in s.band_seconds.size():
			total_band += s.band_seconds[i]
			if i >= 1:
				band_live += s.band_seconds[i]
		out.append("%s: %.0f%% of live play sat in Heat band 1+ (%d raids over %d Nights, "
				% [id, 100.0 * band_live / maxf(total_band, 1.0),
				s.raids_survived + s.raids_lost, c.nights_played]
				+ "%.2f per Night)" % (float(s.raids_survived + s.raids_lost)
				/ maxf(float(c.nights_played), 1.0)))
		if s.meetings > 0:
			out.append("%s: %d Family Meetings, %.1f%% of live play at ×2 (%d back-room "
					% [id, s.meetings, 100.0 * c.meeting_seconds / maxf(c.active_seconds, 1.0),
					s.meeting_jackpots] + "jackpots worth %s)" % s.meeting_paid.text())
		else:
			out.append("%s: the back room never opened — no Family Meeting all career" % id)
		if s.wire_draws > 0:
			var wire_group: Variant = s.total_by_group.get(&"wire", null)
			var wire_total: BigMoney = wire_group as BigMoney if wire_group is BigMoney \
					else BigMoney.zero()
			out.append("%s: %d Wire draws, %d hits, %d exact — %s paid, which is %s of the "
					% [id, s.wire_draws, s.wire_hits, s.wire_exacts, s.wire_paid.text(),
					_pct(s.wire_paid, wire_total)]
					+ "whole `wire` line. A draw pays ×6 of tonight's spinner line at its BASE "
					+ "value and is paid flat, so neither the Heat band nor a Meeting is on "
					+ "that money twice")
		if s.raids_at_open > 0:
			out.append("%s: %d Nights opened with the Heat meter's raid latch already set "
					% [id, s.raids_at_open]
					+ "(the meter crosses 100 at The Count too) — the Inspector was waiting at "
					+ "the door and the raid began on the first serve")
		if s.boss_nights > 0:
			out.append("%s: the Commission cost %d Nights (%d fights won); the ☆ were in the "
					% [id, s.boss_nights, s.boss_wins]
					+ "bank but the rank was not for %d Nights" % s.rank_gated_nights)
	return out


static func _unpriceable(ids: PackedStringArray, catalog: Upgrades) -> PackedStringArray:
	var out: PackedStringArray = []
	for id in ids:
		var node := catalog.def(id)
		if node.is_empty():
			continue
		var priced := false
		for effect: Variant in node["effects"] as Array:
			if PRICEABLE.has(String((effect as Dictionary)["kind"])):
				priced = true
		if not priced:
			out.append(id)
	return out


# --- M2 tables ---------------------------------------------------------------------------


## The deck's whole book. `EV` is realized: what a dollar staked actually came back as, over
## the career — the number the design's "+2–5% at max Influence investment" is a claim about.
static func _club_table(careers: Dictionary, md: bool) -> String:
	var head := PackedStringArray(["profile", "visits/night", "climb rate", "deck %", "spins",
			"win %", "action", "paid", "EV real", "EV wheel", "avg ×", "holds", "coolers",
			"jackpots", "meetings/night", "meeting %"])
	var rows: Array[PackedStringArray] = []
	for id in SimProfile.ids():
		if not careers.has(id) or (careers[id] as Array).is_empty():
			continue
		var c := (careers[id] as Array)[0] as SimCareer
		var s := c.state
		var nights := maxf(float(c.nights_played), 1.0)
		var ev_real := 0.0
		var action := s.casino_staked.add(s.casino_comped_staked)
		if action.is_positive():
			ev_real = s.casino_paid.ratio_to(action) - 1.0
		rows.append(PackedStringArray([
			id,
			"%.2f" % (float(s.deck_visits) / nights),
			"%.0f%%" % (100.0 * float(s.deck_visits) / maxf(float(s.stair_attempts), 1.0)),
			"%.0f%%" % (100.0 * c.deck_seconds / maxf(c.active_seconds, 1.0)),
			str(s.casino_spins),
			"%.0f%%" % (100.0 * float(s.casino_wins) / maxf(float(s.casino_spins), 1.0)),
			action.text(), s.casino_paid.text(),
			"%+.1f%%" % (ev_real * 100.0),
			"%+.1f%%" % (Casino.expected_value(s.stats) * 100.0),
			"%.2f" % (s.casino_mult_sum / maxf(float(s.casino_wins), 1.0)),
			str(s.high_roller_holds), str(s.casino_coolers),
			str(s.jackpots),
			"%.2f" % (float(s.meetings) / nights),
			"%.1f%%" % (100.0 * c.meeting_seconds / maxf(c.active_seconds, 1.0)),
		]))
	return _render(head, rows, md)


## Every dollar of clean the career ever earned, split by where it came from. The pocket-money
## grace and the wash are dirty-that-became-clean; everything else never was dirty.
static func _clean_table(careers: Dictionary, md: bool) -> String:
	var head := PackedStringArray(["profile", "clean earned", "pocket", "washed", "casino",
			"jackpot", "meeting", "wire", "boss", "raid", "direct %"])
	var rows: Array[PackedStringArray] = []
	for id in SimProfile.ids():
		if not careers.has(id) or (careers[id] as Array).is_empty():
			continue
		var s := ((careers[id] as Array)[0] as SimCareer).state
		var total := s.total_clean_earned
		var washed := total.sub_clamped(s.total_clean_direct)
		rows.append(PackedStringArray([
			id, total.text(),
			_pct(s.total_pocket, total),
			_pct(washed.sub_clamped(s.total_pocket), total),
			_pct(_clean_from(s, &"roulette_wheel"), total),
			_pct(_clean_from(s, &"slot_reels"), total),
			_pct(_clean_from(s, &"meeting"), total),
			_pct(_clean_from(s, &"wire"), total),
			_pct(_clean_from(s, &"commission"), total),
			_pct(_clean_from(s, &"raid"), total),
			_pct(s.total_clean_direct, total),
		]))
	return _render(head, rows, md)


## Is the risk system alive? Peak heat is a spike; band seconds are a life.
static func _heat_table(careers: Dictionary, md: bool) -> String:
	var head := PackedStringArray(["profile", "peak", "band 0", "band 1", "band 2", "band 3",
			"raid band", "raids", "survived", "insured", "raids/Night", "at open", "bribes"])
	var rows: Array[PackedStringArray] = []
	for id in SimProfile.ids():
		if not careers.has(id) or (careers[id] as Array).is_empty():
			continue
		var c := (careers[id] as Array)[0] as SimCareer
		var s := c.state
		var total := 0.0
		for b in s.band_seconds:
			total += b
		var cells := PackedStringArray([id, "%.0f" % s.peak_heat])
		for b in s.band_seconds:
			cells.append("%.0f%%" % (100.0 * b / maxf(total, 1.0)))
		cells.append(str(s.raids_survived + s.raids_lost))
		cells.append(str(s.raids_survived))
		cells.append(str(s.raids_insured))
		cells.append("%.2f" % (float(s.raids_survived + s.raids_lost)
				/ maxf(float(c.nights_played), 1.0)))
		cells.append(str(s.raids_at_open))
		cells.append(str(s.bribes_total))
		rows.append(cells)
	return _render(head, rows, md)


## What the rank gates cost: Nights spent in a fight, and days the ☆ were in the bank but the
## rank was not (`Commission.rank_cap`).
static func _commission_table(careers: Dictionary, md: bool) -> String:
	var head := PackedStringArray(["profile", "fight Nights", "won", "sammy tries",
			"butcher tries", "purse", "gated Nights", "gated days", "R4 at", "R5 at"])
	var rows: Array[PackedStringArray] = []
	for id in SimProfile.ids():
		if not careers.has(id) or (careers[id] as Array).is_empty():
			continue
		var c := (careers[id] as Array)[0] as SimCareer
		var s := c.state
		var per_day := float(c.nights_played) / maxf(float(c.days), 1.0)
		rows.append(PackedStringArray([
			id, str(s.boss_nights), str(s.boss_wins),
			str(s.commission.attempts_at(Commission.SAMMY)),
			str(s.commission.attempts_at(Commission.BUTCHER)),
			s.boss_purse.text(), str(s.rank_gated_nights),
			"%.2f" % (float(s.rank_gated_nights) / maxf(per_day, 0.01)),
			_rank_day(c, 4), _rank_day(c, 5),
		]))
	return _render(head, rows, md)


## Late-career income, which is what a T6/T7 cost band has to be priced against.
static func _income_table(careers: Dictionary, md: bool) -> String:
	var head := PackedStringArray(["profile", "clean day 7", "clean day 10", "clean day 14",
			"clean/Night d14", "clean held d14", "lifetime clean", "rank d14"])
	var rows: Array[PackedStringArray] = []
	for id in SimProfile.ids():
		if not careers.has(id) or (careers[id] as Array).is_empty():
			continue
		var c := (careers[id] as Array)[0] as SimCareer
		var last: Dictionary = c.rows[c.rows.size() - 1] if not c.rows.is_empty() else {}
		var nights := maxf(float(last.get("nights", 1)), 1.0)
		rows.append(PackedStringArray([
			id, _day_clean(c, 7), _day_clean(c, 10), _day_clean(c, 14),
			(_day_clean_big(c, 14)).div(nights).text(),
			(last.get("clean_held", BigMoney.zero()) as BigMoney).text(),
			c.state.total_clean_earned.text(),
			"R%d" % int(last.get("rank", 0)),
		]))
	return _render(head, rows, md)


static func _clean_from(s: SimState, source: StringName) -> BigMoney:
	var v: Variant = s.clean_direct_from.get(source, null)
	return v as BigMoney if v is BigMoney else BigMoney.zero()


static func _pct(part: BigMoney, whole: BigMoney) -> String:
	if not whole.is_positive():
		return "—"
	return "%.1f%%" % (part.ratio_to(whole) * 100.0)


static func _rank_day(c: SimCareer, rank: int) -> String:
	var t := c.rank_clock(rank)
	return "—" if t < 0.0 else "day %d" % (int(floor(t / 86400.0)) + 1)


static func _day_clean_big(c: SimCareer, day: int) -> BigMoney:
	for r in c.rows:
		if int(r["day"]) == day:
			return r["clean_day"]
	return BigMoney.zero()


static func _day_clean(c: SimCareer, day: int) -> String:
	return _day_clean_big(c, day).text()


# --- tables ---------------------------------------------------------------------------


static func _career_table(c: SimCareer, md: bool) -> String:
	var head := PackedStringArray(["day", "rank", "☆", "nights", "dirty/day", "clean/day",
			"held dirty", "held clean", "nodes", "play"])
	var rows: Array[PackedStringArray] = []
	for r in c.rows:
		rows.append(PackedStringArray([
			str(r["day"]), "R%d" % int(r["rank"]), str(r["respect"]), str(r["nights"]),
			(r["dirty_day"] as BigMoney).text(), (r["clean_day"] as BigMoney).text(),
			(r["dirty_held"] as BigMoney).text(), (r["clean_held"] as BigMoney).text(),
			"%d/%d" % [int(r["nodes"]), int(r["levels"])],
			"%.0fm" % (float(r["play_seconds"]) / MINUTE),
		]))
	return _render(head, rows, md)


static func _profile_line(runs: Array) -> String:
	var c := runs[0] as SimCareer
	var ranks := PackedStringArray()
	for rank in range(1, 8):
		var t := c.rank_clock(rank)
		if t >= 0.0:
			ranks.append("R%d @ %.1fh" % [rank, t / HOUR])
	return "  %d seeds · median Night %.1f min · active %s/h · idle %s/h · %s" % [
			runs.size(), c.median_night_seconds() / MINUTE, c.last_day_per_hour().text(),
			c.idle_per_hour().text(), " · ".join(ranks) if ranks.size() > 0 else "no rank-ups"]


static func _group_table(c: SimCareer, md: bool) -> String:
	var head := PackedStringArray(["source", "career dirty", "share"])
	var total := _career_dirty(c)
	var by_group := c.state.total_by_group
	var keys: Array = by_group.keys()
	keys.sort_custom(func(a: Variant, b: Variant) -> bool:
		return (by_group[a] as BigMoney).cmp(by_group[b] as BigMoney) > 0)
	var rows: Array[PackedStringArray] = []
	for g: Variant in keys:
		var amount: BigMoney = by_group[g]
		rows.append(PackedStringArray([String(g), amount.text(),
				"%.1f%%" % (amount.ratio_to(total) * 100.0)]))
	var idle := c.state.total_idle
	rows.append(PackedStringArray(["idle (rackets + Safe)", idle.text(),
			"%.1f%%" % (idle.ratio_to(total) * 100.0)]))
	return _render(head, rows, md)


static func _purchase_table(c: SimCareer, md: bool) -> String:
	var head := PackedStringArray(["#", "night", "node", "lvl", "cost", "rank", "play"])
	var rows: Array[PackedStringArray] = []
	var i := 0
	for p in c.state.purchases:
		i += 1
		rows.append(PackedStringArray([str(i), str(int(p["night"])), String(p["id"]),
				str(int(p["level"])), (p["cost"] as BigMoney).text(), "R%d" % int(p["rank"]),
				"%.0fm" % (float(p["play"]) / MINUTE)]))
	if rows.is_empty():
		return "_nothing was ever bought._"
	return _render(head, rows, md)


static func _targets_table(targets: Array[Dictionary], md: bool) -> String:
	var head := PackedStringArray(["profile", "metric", "target", "measured", "verdict", "note"])
	var rows: Array[PackedStringArray] = []
	for t in targets:
		rows.append(PackedStringArray([String(t["profile"]), String(t["metric"]),
				String(t["target"]), String(t["got"]), String(t["verdict"]), String(t["note"])]))
	return _render(head, rows, md)


static func _profile_table(careers: Dictionary, md: bool) -> String:
	var head := PackedStringArray(["profile", "ball s", "sw/s", "tilt", "skill", "discipline",
			"spin kick", "wash", "sessions/day", "nights"])
	var rows: Array[PackedStringArray] = []
	for id in SimProfile.ids():
		if not careers.has(id) or (careers[id] as Array).is_empty():
			continue
		var p := ((careers[id] as Array)[0] as SimCareer).profile
		rows.append(PackedStringArray([p.label, "%.0f" % p.ball_seconds_mean,
				"%.1f" % p.switches_per_sec, "%.0f%%" % (p.tilt_per_ball * 100.0),
				"%.0f%%" % (p.skill_shot_p * 100.0), "%.0f%%" % (p.target_discipline * 100.0),
				"%.0f" % p.spinner_kick_speed, "%.0f%%" % (p.wash_share * 100.0),
				"%.1f" % p.sessions_per_day, str(p.nights_per_session)]))
	return _render(head, rows, md)


# --- helpers ----------------------------------------------------------------------------


static func _career_dirty(c: SimCareer) -> BigMoney:
	return c.state.total_dirty


## Where the ☆ came from, biggest first — the rank ladder is only as sane as this mix.
static func _respect_mix(s: SimState) -> String:
	var keys: Array = s.total_respect_from.keys()
	keys.sort_custom(func(a: Variant, b: Variant) -> bool:
		return int(s.total_respect_from[a]) > int(s.total_respect_from[b]))
	var parts := PackedStringArray()
	for k: Variant in keys:
		parts.append("%s %.0f%%" % [String(k),
				100.0 * float(s.total_respect_from[k]) / maxf(float(s.respect), 1.0)])
	return ", ".join(parts)


static func _top_group(c: SimCareer) -> Dictionary:
	var total := _career_dirty(c)
	var best := BigMoney.zero()
	var name := ""
	for g: Variant in c.state.total_by_group:
		var amount: BigMoney = c.state.total_by_group[g]
		if amount.cmp(best) > 0:
			best = amount
			name = String(g)
	if name == "" or not total.is_positive():
		return {}
	return {"group": name, "amount": best, "share": best.ratio_to(total)}


static func _seed_text(seeds: PackedInt64Array) -> String:
	var out := PackedStringArray()
	for s in seeds:
		out.append(str(s))
	return ", ".join(out)


static func _render(head: PackedStringArray, rows: Array[PackedStringArray], md: bool) -> String:
	var widths: PackedInt32Array = []
	for h in head:
		widths.append(h.length())
	for r in rows:
		for i in r.size():
			if i < widths.size():
				widths[i] = maxi(widths[i], r[i].length())
	var out := PackedStringArray()
	out.append(_line(head, widths, md))
	if md:
		var sep := PackedStringArray()
		for w in widths:
			sep.append("-".repeat(maxi(w, 3)))
		out.append(_line(sep, widths, true))
	else:
		var sep2 := PackedStringArray()
		for w in widths:
			sep2.append("-".repeat(w))
		out.append(_line(sep2, widths, false))
	for r in rows:
		out.append(_line(r, widths, md))
	return "\n".join(out)


static func _line(cells: PackedStringArray, widths: PackedInt32Array, md: bool) -> String:
	var parts := PackedStringArray()
	for i in cells.size():
		var w := widths[i] if i < widths.size() else cells[i].length()
		parts.append(cells[i].rpad(w))
	if md:
		return "| " + " | ".join(parts) + " |"
	return "  " + "  ".join(parts)
